<?php

/*********************************************************************
* Extension configuration file for ext "dd_filename2title".
*
* Generated by ext 29-09-2016 10:03 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Populate file title from the file name',
  'description' => 'Sets file title to the file name on upload if no other metada extractor came with anything more useful. See https://forge.typo3.org/issues/61106',
  'category' => 'services',
  'version' => '1.0.0',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearcacheonload' => 0,
  'author' => 'Dmitry Dulepov',
  'author_email' => 'dmitry.dulepov@gmail.com',
  'author_company' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.2.0-8.3.999',
      'php' => '5.6.0-7.0.999',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'comment' => 'Initial upload',
  'user' => 'dmitry',
);

?>